### ISSUE TITLE
Enhancing BioPAXtoGO Processing Pipeline and Output Stage: Basic workflow and structure

### ISSUE THREAD

**Issue by tmushayahama** [tmushayahama/pathways2GOpy#2]
### Todos

- [x] Define data model to be shared 
- [x] Define structure
- [ ] implement parsing stage
  - [ ] reactome parser
  - [ ] yeast parser
- [ ] Implement mapping stage
- [ ] Implement derivation stage
- [ ] Implement output stage
   - [ ] ttl
   - [ ] visualization 

### Input Stage

- Retrieve the list of BioPAX OWL files from the designated folder or just one file for now, we can determine if folder or file from code
- Tell us which BioPAX file type it is, so a right parser is used. So far **reactome** and **yeast**. Not sure if there is a way to know without user input
- Load each file and extract the necessary data for further processing.
- Load all mapping object by type **reactome** or **yeast**  so that we don't  load repeatedly per each file,

### Parsing Stage

- Convert the extracted data from the BioPAX format to an intermediate representation that facilitates manipulation and processing.
    - if derivation needs more data from the file, we can add it to the intermediate data model. Maybe for determining small molecules, filtering reactions etc. So far the data model is minimal
- Create appropriate data structures or objects to hold the parsed information.

### Mapping Stage

- Implement mappings to transform specific values based on predefined rules or conditions. Usually value1 to value2
- Define logic to map values such as **URS0000A0AC1F_559292** to r**RNA** according to the required transformations.

### Derivation Stage (idk what to call this maybe transformation )

- Utilize the parsed and mapped data to derive new values or perform calculations.
- These are like rules, small molecules, filtering drugs, whatever SPARQL was doing
- Implement algorithms or rules to derive values based on the provided input.
   - whatever SPARQL was doing

### Output Stage

Main purpose is ttl format, but we can enhnace testing and visualization capabilities

- Enhance the output stage to support additional functionalities and testing capabilities.
- Convert the processed data into the desired ttl format.
- Integrate visualization tools like NetworkX or Pyvis to generate visual representations of the processed data for testing and analysis purposes.
- Write the ttl file to the designated output folder for noctua
   - mainly using gocam_gen

tagging @dustine32
